# Generated by Django 4.0.1 on 2022-02-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_foodcard_category_productscart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productscart',
            options={'verbose_name': 'Categories', 'verbose_name_plural': 'Category'},
        ),
    ]
